FROM nginx:alpine

RUN apk add --no-cache --virtual .acme-deps \
        libffi \
        libssl1.1 \
        openssl \
        ca-certificates \
        binutils bash

RUN apk add --no-cache --virtual .build-deps \
        linux-headers \
        openssl-dev \
        musl-dev \
        libffi-dev && \
        apk del .build-deps

ADD https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh /acme.sh

RUN chmod +x /acme.sh && \
    mkdir /acme-data && \
    ./acme.sh --install --config-home /acme-data
