FROM nginx:alpine

ADD https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh /acme.sh

RUN apk add --no-cache --virtual .acme-deps \
        libffi \
        libssl1.1 \
        openssl \
        ca-certificates \
        binutils bash

RUN apk add --no-cache --virtual .build-deps \
        linux-headers \
        openssl-dev \
        musl-dev \
        libffi-dev && \
        chmod +x /acme.sh && \
        INSTALLONLINE=1 sh /acme.sh && \
        apk del .build-deps
